// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Knoq.Users.Item.Groups
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetRelationQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "admins")]
        #pragma warning disable CS1591
        Admins,
        #pragma warning restore CS1591
        [EnumMember(Value = "belongs")]
        #pragma warning disable CS1591
        Belongs,
        #pragma warning restore CS1591
        [EnumMember(Value = "belongs-or-admins")]
        #pragma warning disable CS1591
        BelongsOrAdmins,
        #pragma warning restore CS1591
        [EnumMember(Value = "attendees")]
        #pragma warning disable CS1591
        Attendees,
        #pragma warning restore CS1591
    }
}
