/*
 * traP knoQ
 *
 * This is a sample knoQ server. 
 *
 * The version of the OpenAPI document: 2.1.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;

namespace Knoq.Client
{
    /// <summary>
    /// A URI builder
    /// </summary>
    class WebRequestPathBuilder(string baseUrl, string path)
    {
        private readonly string _baseUrl = (baseUrl[^1] == '/') ? baseUrl[..^1] : baseUrl;
        private string _path = path;
        private string _query = "?";

        public void AddPathParameters(Dictionary<string, string> parameters)
        {
            foreach (var parameter in parameters)
            {
                _path = _path.Replace("{" + parameter.Key + "}", Uri.EscapeDataString(parameter.Value));
            }
        }

        public void AddQueryParameters(Multimap<string, string> parameters)
        {
            foreach (var parameter in parameters)
            {
                foreach (var value in parameter.Value)
                {
                    _query = _query + parameter.Key + "=" + Uri.EscapeDataString(value) + "&";
                }
            }
        }

        public string GetFullUri()
        {
            return _baseUrl + _path + _query[..^1];
        }
    }
}
