version: '3'

tasks:
  default:
    - task: generate-client

  generate-client:
    aliases:
      - gen
    desc: Generates C# API client
    summary: Generates C# client for knoQ API from OpenAPI spec with Microsoft Kiota
    env:
      KNOQ_TAG_NAME: master
      CLIENT_NAMESPACE: Knoq
      CLIENT_CLASS_NAME: KnoqApiClient
    vars:
      OPENAPI_SPEC_URL: https://raw.githubusercontent.com/traPtitech/knoQ/${KNOQ_TAG_NAME}/docs/swagger.yaml
    preconditions:
      - sh: "[[ $(curl -w \"%{http_code}\" {{.OPENAPI_SPEC_URL}}) = *200 ]]"
        msg: Checks if OpenAPI spec is available
    cmds:
      - |
        echo "TargetTagName: ${KNOQ_TAG_NAME}"
      - |
        docker run -u 0:0 --rm -v "${PWD}/src/${CLIENT_NAMESPACE}":/local \
        mcr.microsoft.com/openapi/kiota generate \
          -d {{.OPENAPI_SPEC_URL}} \
          -o /local \
          -l CSharp \
          -c ${CLIENT_CLASS_NAME} \
          -n ${CLIENT_NAMESPACE} \
          --clear-cache
