// <auto-generated/>
#pragma warning disable CS0618
using Knoq.Ical.V1.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Knoq.Ical.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \ical\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Knoq.ical.v1.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Knoq.Ical.V1.Item.WithIcalTokenItemRequestBuilder"/></returns>
        public global::Knoq.Ical.V1.Item.WithIcalTokenItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("icalToken", position);
                return new global::Knoq.Ical.V1.Item.WithIcalTokenItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Knoq.Ical.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ical/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Knoq.Ical.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ical/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
