// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Knoq.Models
{
    /// <summary>pending or absent or attendance</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestSchedule_schedule
    {
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "absent")]
        #pragma warning disable CS1591
        Absent,
        #pragma warning restore CS1591
        [EnumMember(Value = "attendance")]
        #pragma warning disable CS1591
        Attendance,
        #pragma warning restore CS1591
    }
}
