// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Knoq.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Knoq.Models.RequestEventInstant"/>, <see cref="global::Knoq.Models.RequestEventStock"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RequestEvent : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Knoq.Models.RequestEventInstant"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Knoq.Models.RequestEventInstant? RequestEventInstant { get; set; }
#nullable restore
#else
        public global::Knoq.Models.RequestEventInstant RequestEventInstant { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Knoq.Models.RequestEventStock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Knoq.Models.RequestEventStock? RequestEventStock { get; set; }
#nullable restore
#else
        public global::Knoq.Models.RequestEventStock RequestEventStock { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Knoq.Models.RequestEvent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Knoq.Models.RequestEvent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Knoq.Models.RequestEvent();
            if("RequestEventInstant".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.RequestEventInstant = new global::Knoq.Models.RequestEventInstant();
            }
            else if("RequestEventStock".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.RequestEventStock = new global::Knoq.Models.RequestEventStock();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(RequestEventInstant != null)
            {
                return RequestEventInstant.GetFieldDeserializers();
            }
            else if(RequestEventStock != null)
            {
                return RequestEventStock.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            if(RequestEventInstant != null)
            {
                writer.WriteObjectValue<global::Knoq.Models.RequestEventInstant>(null, RequestEventInstant);
            }
            else if(RequestEventStock != null)
            {
                writer.WriteObjectValue<global::Knoq.Models.RequestEventStock>(null, RequestEventStock);
            }
        }
    }
}
#pragma warning restore CS0618
