// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Knoq.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ResponseEventDetail : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>編集権を持つユーザー</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? Admins { get; set; }
#nullable restore
#else
        public List<Guid?> Admins { get; set; }
#endif
        /// <summary>The attendees property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Knoq.Models.ResponseEventDetail_attendees>? Attendees { get; set; }
#nullable restore
#else
        public List<global::Knoq.Models.ResponseEventDetail_attendees> Attendees { get; set; }
#endif
        /// <summary>The createdAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The createdBy property</summary>
        public Guid? CreatedBy { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The eventId property</summary>
        public Guid? EventId { get; set; }
        /// <summary>The group property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Knoq.Models.ResponseGroup? Group { get; set; }
#nullable restore
#else
        public global::Knoq.Models.ResponseGroup Group { get; set; }
#endif
        /// <summary>The groupName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupName { get; set; }
#nullable restore
#else
        public string GroupName { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>グループ外のユーザーが参加予定を出来るか</summary>
        public bool? Open { get; set; }
        /// <summary>The place property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Place { get; set; }
#nullable restore
#else
        public string Place { get; set; }
#endif
        /// <summary>The room property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Knoq.Models.ResponseRoom? Room { get; set; }
#nullable restore
#else
        public global::Knoq.Models.ResponseRoom Room { get; set; }
#endif
        /// <summary>部屋の共用をするか</summary>
        public bool? SharedRoom { get; set; }
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Knoq.Models.ResponseEventDetail_tags>? Tags { get; set; }
#nullable restore
#else
        public List<global::Knoq.Models.ResponseEventDetail_tags> Tags { get; set; }
#endif
        /// <summary>The timeEnd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeEnd { get; set; }
#nullable restore
#else
        public string TimeEnd { get; set; }
#endif
        /// <summary>The timeStart property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeStart { get; set; }
#nullable restore
#else
        public string TimeStart { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Knoq.Models.ResponseEventDetail"/> and sets the default values.
        /// </summary>
        public ResponseEventDetail()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Knoq.Models.ResponseEventDetail"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Knoq.Models.ResponseEventDetail CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Knoq.Models.ResponseEventDetail();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "admins", n => { Admins = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
                { "attendees", n => { Attendees = n.GetCollectionOfObjectValues<global::Knoq.Models.ResponseEventDetail_attendees>(global::Knoq.Models.ResponseEventDetail_attendees.CreateFromDiscriminatorValue)?.AsList(); } },
                { "createdAt", n => { CreatedAt = n.GetStringValue(); } },
                { "createdBy", n => { CreatedBy = n.GetGuidValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "eventId", n => { EventId = n.GetGuidValue(); } },
                { "group", n => { Group = n.GetObjectValue<global::Knoq.Models.ResponseGroup>(global::Knoq.Models.ResponseGroup.CreateFromDiscriminatorValue); } },
                { "groupName", n => { GroupName = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "open", n => { Open = n.GetBoolValue(); } },
                { "place", n => { Place = n.GetStringValue(); } },
                { "room", n => { Room = n.GetObjectValue<global::Knoq.Models.ResponseRoom>(global::Knoq.Models.ResponseRoom.CreateFromDiscriminatorValue); } },
                { "sharedRoom", n => { SharedRoom = n.GetBoolValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfObjectValues<global::Knoq.Models.ResponseEventDetail_tags>(global::Knoq.Models.ResponseEventDetail_tags.CreateFromDiscriminatorValue)?.AsList(); } },
                { "timeEnd", n => { TimeEnd = n.GetStringValue(); } },
                { "timeStart", n => { TimeStart = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<Guid?>("admins", Admins);
            writer.WriteCollectionOfObjectValues<global::Knoq.Models.ResponseEventDetail_attendees>("attendees", Attendees);
            writer.WriteStringValue("createdAt", CreatedAt);
            writer.WriteGuidValue("createdBy", CreatedBy);
            writer.WriteStringValue("description", Description);
            writer.WriteGuidValue("eventId", EventId);
            writer.WriteObjectValue<global::Knoq.Models.ResponseGroup>("group", Group);
            writer.WriteStringValue("groupName", GroupName);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("open", Open);
            writer.WriteStringValue("place", Place);
            writer.WriteObjectValue<global::Knoq.Models.ResponseRoom>("room", Room);
            writer.WriteBoolValue("sharedRoom", SharedRoom);
            writer.WriteCollectionOfObjectValues<global::Knoq.Models.ResponseEventDetail_tags>("tags", Tags);
            writer.WriteStringValue("timeEnd", TimeEnd);
            writer.WriteStringValue("timeStart", TimeStart);
            writer.WriteStringValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
